version: '3.6'
services:
  discord-bot:
    container_name: discord-bot
    image: ghcr.io/code4govtech/discord-bot:main
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.26.0.1:12201"
        tag: discord-bot
    networks:
      - logstash_common
    environment:
      TOKEN: ${TOKEN}
      SERVER_ID: ${SERVER_ID}
      INTRODUCTIONS_CHANNEL: ${INTRODUCTIONS_CHANNEL}
      NON_CONTRIBUTOR_ROLES: ${NON_CONTRIBUTOR_ROLES}
      FLASK_HOST: ${FLASK_HOST}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      VERIFIED_ROLE_ID: ${VERIFIED_ROLE_ID}
      GITHUB_AUTHENTICATION_URL: ${GITHUB_AUTHENTICATION_URL}

networks:
  logstash_common:
    external: true
